project:
  type: website

website:
  title: "My Quarto Website"
  description: "A website created with Quarto"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Cards
        href: cards.qmd
      - text: Card clean
        href: card_clean.qmd
    right:
      - icon: github
        href: https://github.com/yourusername/your-repo

format:
  html:
    theme: default
    css: styles.css
    toc: true
    toc-depth: 2
    number-sections: true

# editor: visual